using System;

namespace _413assignment3.Models
{
    /// <summary>
    /// Default Error view generated by MVC
    /// </summary>
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
